name: Build iOS App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Archive app
        run: |
          xcodebuild -scheme HelloSwiftApp -sdk iphoneos -configuration Release -archivePath build/HelloSwiftApp.xcarchive archive

      - name: Export .ipa
        run: |
          mkdir -p build/ipa
          xcodebuild -exportArchive -archivePath build/HelloSwiftApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build/ipa

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: HelloSwiftApp-ipa
          path: build/ipa/*.ipa